org: himkwtn
app: amity-fiercekathon
service: amity-fiercekathon
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1

plugins:
  - serverless-offline
  - serverless-lift

constructs:
  migrate-queue:
    type: queue
    worker:
      handler: handler.migrateWorker
      environment:
        USER_QUEUE: ${construct:user-queue.queueUrl}
        POST_QUEUE: ${construct:post-queue.queueUrl}
  user-queue:
    type: queue
    worker:
      handler: handler.createUserWorker
  post-queue:
    type: queue
    worker:
      handler: handler.createPostWorker

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

  migrate:
    handler: handler.migrate
    events:
      - httpApi:
          path: /migrate
          method: get
    environment:
      MIGRATE_QUEUE: ${construct:migrate-queue.queueUrl}
