org: himkwtn
app: amity-fiercekathon
service: amity-fiercekathon
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1

plugins:
  - serverless-offline
  - serverless-lift

constructs:
  user-queue:
    type: queue
    worker:
      handler: handler.createUserWorker
  post-queue:
    type: queue
    worker:
      handler: handler.createPostWorker

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

  createUserQueue:
    handler: handler.createUserQueue
    events:
      - httpApi:
          path: /users-queue
          method: post
    environment:
      QUEUE_URL: ${construct:user-queue.queueUrl}

  createUser:
    handler: handler.createUser
    events:
      - httpApi:
          path: /users
          method: post

  createPost:
    handler: handler.createPost
    events:
      - httpApi:
          path: /posts
          method: post
